source 'https://rubygems.org'

gem 'cucumber'
gem 'pry'
gem 'rake'
gem 'appium_lib', '10.5.0'
gem 'parallel_cucumber', path: '/Users/rajdeepvarma/projects/parallel_cucumber'
gem 'calabash-android'
gem 'irb'
gem 'xpath'